name = "clipclash-twitch-refresh"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[triggers]
crons = ["0 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "clipclash-db"
database_id = "REPLACE_ME"
