name = "tiktokolympics-rooms"
main = "src/index.ts"
compatibility_date = "2026-01-16"

[durable_objects]
bindings = [{ name = "ROOMS_DO", class_name = "RoomsDO" }]

[[migrations]]
tag = "v1"
new_classes = ["RoomsDO"]
